name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: trace

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build `crabnet`
      run: cargo build --verbose
    - name: Run tests for `crabnet`
      run: cargo test --verbose
    - name: Build `crabnet_tcp`
      run: cargo build --verbose --manifest-path crabnet_tcp/Cargo.toml
    - name: Run tests for `crabnet_tcp`
      run: cargo test --verbose --manifest-path crabnet_tcp/Cargo.toml
