name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: trace

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build `crabnet`
      run: cargo build --verbose
    - name: Run tests for `crabnet`
      run: cargo test --verbose
    - name: Build `crabnet_tcp`
      run: cargo build --verbose --manifest-path crabnet_tcp/Cargo.toml
    - name: Run tests for `crabnet_tcp`
      run: cargo test --verbose --manifest-path crabnet_tcp/Cargo.toml
    - name: Build documentation for `crabnet` and `crabnet_tcp`
      run: |
        cargo doc --all --verbose
        echo "<meta http-equiv=\"refresh\" content=\"0; url=crabnet\">" > ./target/doc/index.html
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/doc
